<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>MPTAndroidTools.Runtime</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ModuleRuntimeRoot>$(MSBuildProjectDirectory)\..\..\modules\android-tools-suite\windows\x64</ModuleRuntimeRoot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AndroidTools.MyPowerTools\AndroidTools.MyPowerTools.csproj" />
    <PackageReference Include="MyPowerTools.Protocol" Version="0.2.0" />
    <PackageReference Include="MyPowerTools.ToolSdk" Version="0.2.0" />
    <ProjectReference Include="..\..\..\..\..\src\MyPowerTools.Ipc.Shared\MyPowerTools.Ipc.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\MyPowerTools.Ipc.AspNetCore\MyPowerTools.Ipc.AspNetCore.csproj" />
  </ItemGroup>

  <Target Name="CopyModuleHostToPackage" AfterTargets="Build">
    <MakeDir Directories="$(ModuleRuntimeRoot)" />
    <ItemGroup>
      <ModuleHostRuntimeFiles Include="$(TargetDir)*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(ModuleHostRuntimeFiles)" DestinationFolder="$(ModuleRuntimeRoot)" SkipUnchangedFiles="true" />
  </Target>

</Project>
